# Generated by Django 3.1.2 on 2021-07-21 15:58

import RouteTracker.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeId', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('initialSOC', models.IntegerField(verbose_name='Initial SOC (%)')),
                ('batteryCapacity', models.IntegerField(verbose_name='Battery Capacity (Kwh)')),
                ('routeTitle', models.CharField(default='', max_length=50, verbose_name='Route Title')),
                ('batteryRating', models.IntegerField(verbose_name='Battery Rating (VDC)')),
                ('fileName', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[RouteTracker.validators.validateFileExtension], verbose_name='Vessel Timetable File')),
                ('thresholdPower', models.IntegerField(null=True, verbose_name='Threshold Power')),
                ('departure', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None, verbose_name='Departure')),
                ('transit', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None, verbose_name='Transit')),
                ('arrival', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None, verbose_name='Arrival')),
                ('stay', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None, verbose_name='Stay')),
                ('calcSOC', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('minDeparturePow', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None, verbose_name='Min Departure Power Req')),
                ('minTransitPow', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None, verbose_name='Min Transit Power Req')),
                ('maxTransitPow', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None, verbose_name='Max Transit Power Req')),
                ('minArrivalPow', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None, verbose_name='Min Arrival Power Req')),
                ('maxArrivalPow', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None, verbose_name='Max Arrival Power Req')),
                ('minStayPow', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None, verbose_name='Min Stay Power Req')),
                ('maxStayPow', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None, verbose_name='Max Stay Power Req')),
            ],
            options={
                'verbose_name': 'Route List',
                'db_table': 'Route',
                'ordering': ['dateAdded'],
            },
        ),
    ]
